# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A6Mw0F7nQmxbmFYy410anIAbDfwxXOLc
"""

# Desalination Efficiency Prediction Project
# Author: Owais Mohammed Abdul Razzaq

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# -----------------------
# 1. Create synthetic dataset (realistic simulation)
# -----------------------

np.random.seed(42)

samples = 500

salinity = np.random.uniform(30000, 45000, samples)       # ppm
temperature = np.random.uniform(20, 35, samples)         # °C
pressure = np.random.uniform(50, 80, samples)            # bar
flow_rate = np.random.uniform(40, 70, samples)           # m3/h
energy = np.random.uniform(3, 6, samples)                # kWh/m3

# Efficiency formula (simulated realistic behavior)
efficiency = (
    100
    - (salinity / 1000)
    + (temperature * 0.3)
    + (pressure * 0.4)
    - (energy * 4)
    + np.random.normal(0, 2, samples)
)

data = pd.DataFrame({
    "Salinity": salinity,
    "Temperature": temperature,
    "Pressure": pressure,
    "FlowRate": flow_rate,
    "EnergyConsumption": energy,
    "Efficiency": efficiency
})

print(data.head())

# -----------------------
# 2. Train-test split
# -----------------------

X = data.drop("Efficiency", axis=1)
y = data["Efficiency"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -----------------------
# 3. Train model
# -----------------------

model = LinearRegression()
model.fit(X_train, y_train)

# -----------------------
# 4. Predictions
# -----------------------

y_pred = model.predict(X_test)

# -----------------------
# 5. Evaluation
# -----------------------

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nModel Performance:")
print("Mean Absolute Error:", round(mae, 2))
print("R2 Score:", round(r2, 3))

# -----------------------
# 6. Test with custom input
# -----------------------

sample_input = pd.DataFrame({
    "Salinity": [38000],
    "Temperature": [28],
    "Pressure": [65],
    "FlowRate": [55],
    "EnergyConsumption": [4.5]
})

prediction = model.predict(sample_input)
print("\nPredicted Efficiency:", round(prediction[0], 2), "%")
# Save dataset to CSV
data.to_csv("desalination_dataset.csv", index=False)
print("Dataset saved as desalination_dataset.csv")
from google.colab import files
files.download("desalination_dataset.csv")